name: lokamotive
description: "BINUS University Software Engineering Project, Developed with love and energy"

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  rive: 0.13.20

  flutter_map: 7.0.2
  flutter_svg: ^2.0.10
  http: ^1.2.2
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  animated_text_kit: ^4.2.3
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  latlong2 : 0.9.1
  google_maps_flutter: 2.10.0
  google_maps_flutter_android: 2.14.11
  google_maps_flutter_platform_interface: 2.9.5
  flutter_plugin_android_lifecycle : 2.0.23
  location: ^5.0.0
  flutter_polyline_points: ^2.0.0
  # google_maps_place_picker_mb: 3.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.


  flutter_lints: ^5.0.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets: 

    - assets/
    - assets/Image/
    - assets/Icon/check_schedule_icon.svg
    - assets/Icon/find_route_icon.svg
    - assets/Image/news_carousel1.png
    - assets/Image/news_carousel2.png
    - assets/Icon/home_icon.svg
    - assets/Icon/route_icon.svg
    - assets/Icon/person_icon.svg
    - assets/iconspng/backRutePage.png
    - assets/iconspng/locationIconRutePage.png
    - assets/iconspng/searchIconRutePage.png
    - assets/test.png
    - assets/iconspng/krlIcon.png
    - assets/iconspng/tjIcon.png





  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
